### ISSUE TITLE
[Bug]: Could not handle query strings at the end of file URL

### ISSUE THREAD

**Issue by mahemmati** [hugomyb/filament-media-action#3]
### What happened?

If the URL ends with query strings ... the action return "Media not supported" for example:
http://localhost/private-media/temp/3/HR-F-01-01.pdf?expires=1722938475&signature=f78684e7ccdba894cf461ba37b34f456a27d5251dac39daec1bf7dfbfdbb7f7b

### How to reproduce the bug

create temp URLs with `expires` and `signature` query strings

### Package Version

latest

### PHP Version

8.3

### Laravel Version

10

**Comment by JibayMcs** [comment]
Hi !

Just fixed in the last release [v3.1.0.4](https://github.com/hugomyb/filament-media-action/releases/tag/v3.1.0.4)

**Comment by mello-joao** [comment]
Hi there,

I'm having a similar issue with an mp4:

**This URL works:**
http://minio:9000/local/events/clips/44fc191b-f674-4a7b-be2d-6356d354ed46.mp4

**This URL doesn't work:**
http://minio:9000/local/events/clips/c44fc191b-f674-4a7b-be2d-6356d354ed46.mp4?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sail%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T055752Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=b9a91fe862f601e7f64ffe8c7c8b692e7f6445ad18fe21c400c4610d0482b376

Thank you,

**Comment by JibayMcs** [comment]
> Hi there,
> 
> I'm having a similar issue with an mp4:
> 
> **This URL works:** http://minio:9000/local/events/clips/44fc191b-f674-4a7b-be2d-6356d354ed46.mp4
> 
> **This URL doesn't work:** http://minio:9000/local/events/clips/c44fc191b-f674-4a7b-be2d-6356d354ed46.mp4?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sail%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T055752Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=b9a91fe862f601e7f64ffe8c7c8b692e7f6445ad18fe21c400c4610d0482b376
> 
> Thank you,

Can you send the request header of your URL ?

**Comment by JibayMcs** [comment]
> Hi there,
> 
> I'm having a similar issue with an mp4:
> 
> **This URL works:** http://minio:9000/local/events/clips/44fc191b-f674-4a7b-be2d-6356d354ed46.mp4
> 
> **This URL doesn't work:** http://minio:9000/local/events/clips/c44fc191b-f674-4a7b-be2d-6356d354ed46.mp4?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sail%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T055752Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=b9a91fe862f601e7f64ffe8c7c8b692e7f6445ad18fe21c400c4610d0482b376
> 
> Thank you,

Fixed in the last release [v3.1.0.6](https://github.com/hugomyb/filament-media-action/releases/tag/v3.1.0.6)
