### ISSUE TITLE
[Bug]: can't view media with error message  "MediaAction::$mime must not be accessed before initialization"

### ISSUE THREAD

**Issue by sayasuhendra** [hugomyb/filament-media-action#4]
### What happened?

when i click action button i got this error

Typed property Hugomyb\FilamentMediaAction\Tables\Actions\MediaAction::$mime must not be accessed before initialization

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/f7ebfd1e-be59-49e0-a190-82b412d95a36">

### How to reproduce the bug

i put your sample ini action array

MediaAction::make('tutorial')
    ->iconButton()
    ->icon('heroicon-o-video-camera')
    ->media('https://www.youtube.com/watch?v=rN9XI9KCz0c&list=PL6tf8fRbavl3jfL67gVOE9rF0jG5bNTMi'),

### Package Version

3.1

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by hugomyb** [comment]
Hi, can you give me a little more information ? Where did you put this Action, please share the code with me and can you show me on the error page you have, on which line there is this error ? 
Thanks

**Comment by hugomyb** [comment]
Fix in the last release [v3.1.0.7](https://github.com/hugomyb/filament-media-action/releases/tag/v3.1.0.7)

Sorry for the inconvenience.
