### ISSUE TITLE
[Bug]: Method Hugomyb\FilamentMediaAction\Tables\Actions\MediaAction::modal does not exist.

### ISSUE THREAD

**Issue by Bellukchips** [hugomyb/filament-media-action#7]
### What happened?

hmmm, from my last issue #6 

i fixed just give comment your code like this

    protected function setUp(): void
    {
        parent::setUp();

        // $this->modal();

        $this->modalSubmitAction(false);

        $this->modalCancelAction(false);

        $this->modalContent(function () {
            return $this->getContentView();
        });
    }

and your package is already running in my app

why is that?

### How to reproduce the bug

y

### Package Version

latest

### PHP Version

8.2.12

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by hugomyb** [comment]
You don't need to comment on this line, just repeat the code I gave you in the last issue and it'll work fine.

**Comment by Bellukchips** [comment]
hmm, but if i uncomment $this->modal error still occurs
Is there any other configuration to be done? Other than the  composer require hugomyb/filament-media-action ?

**Comment by hugomyb** [comment]
Show me your code again please

**Comment by Bellukchips** [comment]
`<?php

namespace App\Filament\Clusters\Audios\Resources;

use App\Filament\Clusters\Audios;
use App\Filament\Clusters\Audios\Resources\AudioResource\Pages;
use App\Filament\Clusters\Audios\Resources\AudioResource\RelationManagers;
use App\Models\Audio\Audio;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Pages\SubNavigationPosition;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class AudioResource extends Resource
{
    protected static ?string $model = Audio::class;

    protected static ?string $navigationIcon = 'heroicon-o-list-bullet';

    protected static ?string $cluster = Audios::class;
    protected static SubNavigationPosition $subNavigationPosition = SubNavigationPosition::End;
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')->required()->maxLength('150'),
                Forms\Components\Select::make('category_id')->relationship('category', 'name')->required(),
                Forms\Components\TextInput::make('link_audio')->url()
                    ->required()
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->sortable()->searchable(),
                Tables\Columns\TextColumn::make('category.name')->sortable()->searchable(),
                Tables\Columns\IconColumn::make('link_audio')->label('Sound')
                    ->boolean()
                    ->trueIcon('heroicon-o-speaker-wave')
                    ->action(
                        \Hugomyb\FilamentMediaAction\Tables\Actions\MediaAction::make('link_audio')
                            ->iconButton()
                            ->media(fn($record) => $record->link_audio),
                    ),

            ])
            ->filters([
                Tables\Filters\SelectFilter::make('category')->relationship('category', 'name'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAudio::route('/'),
            'create' => Pages\CreateAudio::route('/create'),
            'edit' => Pages\EditAudio::route('/{record}/edit'),
        ];
    }
}
`

this my code


its work when i comment $this->modal()

**Comment by Bellukchips** [comment]
![Screenshot 2024-09-23 164929](https://github.com/user-attachments/assets/090c6d18-9475-4d12-bb75-961a3b0cea49)

**Comment by hugomyb** [comment]
Your code works perfectly on my side.

Which package version are you using ? latest ?

**Comment by Bellukchips** [comment]
yaa, i use version latest

this my composer

`  "require": {
        "php": "^8.1",
        "filament/filament": "3.2",
        "guzzlehttp/guzzle": "^7.2",
        "hugomyb/filament-media-action": "^3.1",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },`

**Comment by hugomyb** [comment]
I've just tested installing the plugin from scratch and everything works fine on my end, maybe try uninstalling and reinstalling it.

**Comment by Bellukchips** [comment]
hmmm, its very unique, i try install new laravel filament and install composer require hugomyb/filament-media-action

the result its same
is the problem with my computer?

**Comment by hugomyb** [comment]
I think so because I've just created a new Laravel project, installed Filament and my package, and everything is working properly... maybe your environment, idk..

**Comment by Bellukchips** [comment]
Did you install with command composer require hugomyb/filament-media-action?

**Comment by Bellukchips** [comment]
> Yes, try `php artisan optimize:clear`, `php artisan filament:clear`, `php artisan filament:assets`

I have tried it, but still with the same error

**Comment by hugomyb** [comment]
However, the ->modal() method does exist in the CanOpenModal trait in Action, from which MediaAction extends: 

```php
public function modal(bool | Closure | null $condition = true): static
    {
        $this->hasModal = $condition;

        return $this;
    }
```
    
I can't imagine why it doesn't work for you...

**Comment by Bellukchips** [comment]
> However, the ->modal() method does exist in the CanOpenModal trait in Action, from which MediaAction extends:
> 
> ```
> public function modal(bool | Closure | null $condition = true): static
>     {
>         $this->hasModal = $condition;
> 
>         return $this;
>     }
> ```
> 
> I can't imagine why it doesn't work for you...

is the code here? https://github.com/hugomyb/filament-media-action/blob/main/src/Concerns/HasMedia.php

**Comment by hugomyb** [comment]
It's not in my code, but in Filament's. My MediaAction class extends filament's Action class, which in turn extends the MountableAction class, which has a “CanOpenModal” trait.

https://github.com/filamentphp/filament/blob/3.x/packages/actions/src/Concerns/CanOpenModal.php#L15

**Comment by Bellukchips** [comment]
I see the code on the DeleteAction button does not contain $this->modal
https://github.com/filamentphp/filament/blob/3.x/packages/tables/src/Actions/DeleteAction.php

**Comment by hugomyb** [comment]
I don't understand, I've just created a brand new project of my own, and it works. Here are the steps I took: 

1. `laravel new media`
2. `composer require filament/filament:"^3.2" -W`
3. `php artisan filament:install --panels`
4. Create user
5. Create UserResource
6. Install `composer require hugomyb/filament-media-action`
7. In my UserResource :
```php
return $table
            ->columns([
                Tables\Columns\IconColumn::make('url')
                    ->icon('heroicon-o-external-link')
                    ->action(MediaAction::make('url')
                        ->media('https://www.youtube.com/watch?v=PrmzB21ZPhw&pp=ygUOMTEzIG91YWlzIGdyb3M%3D'))
            ])
```

Result, it's working : 
![image](https://github.com/user-attachments/assets/ba6feb8a-5c6d-486c-bc90-84d25c6367a3)

**Comment by Bellukchips** [comment]
> I don't understand, I've just created a brand new project of my own, and it works. Here are the steps I took:
> 
> 1. `laravel new media`
> 2. `composer require filament/filament:"^3.2" -W`
> 3. `php artisan filament:install --panels`
> 4. Create user
> 5. Create UserResource
> 6. Install `composer require hugomyb/filament-media-action`
> 7. In my UserResource :
> 
> ```
> return $table
>             ->columns([
>                 Tables\Columns\IconColumn::make('url')
>                     ->icon('heroicon-o-external-link')
>                     ->action(MediaAction::make('url')
>                         ->media('https://www.youtube.com/watch?v=PrmzB21ZPhw&pp=ygUOMTEzIG91YWlzIGdyb3M%3D'))
>             ])
> ```
> 
> Result, it's working : ![image](https://private-user-images.githubusercontent.com/92823242/369905423-ba6feb8a-5c6d-486c-bc90-84d25c6367a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDYyMDMsIm5iZiI6MTcyNzE0NTkwMywicGF0aCI6Ii85MjgyMzI0Mi8zNjk5MDU0MjMtYmE2ZmViOGEtNWM2ZC00ODZjLWJjOTAtODRkMjVjNjM2N2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyNDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MWJjMTM5Y2RhZDVhNzBhNDA5ZGI4MDliNTFiZTYyNzIwOWM1NTU1NzE1NzMyYTYyNmQ1MmJkZTcxZGM4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3ALDRgnESuxUDD3hUj7xteNhCH9YBhUKqJoJwNEfSRM)

can you share for me? your example

**Comment by hugomyb** [comment]
I've deleted it, add me to your project, I'll take a look and see if it works for me

**Comment by Bellukchips** [comment]
> ```
>  Tables\Columns\IconColumn::make('url')
>                     ->icon('heroicon-o-external-link')
>                     ->action(MediaAction::make('url')
>                         ->media('https://www.youtube.com/watch?v=PrmzB21ZPhw&pp=ygUOMTEzIG91YWlzIGdyb3M%3D'))
> ```

sure, this my repo https://github.com/Bellukchips/sampe-filament-media-action.git

you can clone and analyst please

**Comment by hugomyb** [comment]
Fixed !

Your composer.json contained `“filament/filament”: “3.2”`, you needed `“filament/filament”: “^3.2”` and do a composer update as I said before. You weren't on the latest version of Filament.

I'll let you do the updating

**Comment by Bellukchips** [comment]
cool, thanks for your time in helping me
