### ISSUE TITLE
[Request]: Autoplay

### ISSUE THREAD

**Issue by willcastillo** [hugomyb/filament-media-action#8]
### What happened?

Hey! Thanks for your plugin.

Any chance you can add autoplay for videos or audio files?

### How to reproduce the bug

not a bug

### Package Version

2

### PHP Version

8

### Laravel Version

11

**Comment by hugomyb** [comment]
Hi! I will try to implement this tomorrow and I will let you know when it is done.

**Comment by hugomyb** [comment]
Feature added in the latest release: [v3.1.0.8](https://github.com/hugomyb/filament-media-action/releases/tag/v3.1.0.8)

**Comment by willcastillo** [comment]
Thank you @hugomyb !
